#######################################################
# Makefile for QT program
# Created by zhiyb @ GT-Soft
#

MOCH = mainw.h misc.h
OBJS = main.o mainw.o misc.o apps.o
TARG = IconMgr

CC = g++
MOC = /root/qt/qt-2.3.10/bin/moc
STRIP = strip
QTDIR = /root/qt/qt-2.3.10

COPT = -I$(QTDIR)/include -pipe -DQWS -fno-exceptions -fno-rtti -Wall -Wsign-compare -W -DNO_DEBUG
BOPT = -L$(QTDIR)/lib -Wl,-rpath,/opt/qt-2.3.10.new/lib -lqte

MOCC = $(addprefix moc_,$(subst .h,.cpp,$(MOCH)))
OBJS += $(subst .cpp,.o,$(MOCC))

$(TARG): $(OBJS)
	$(CC) $(BOPT) -o $(TARG) $(OBJS)
	$(STRIP) $(TARG)

$(OBJS): %.o: %.cpp
	$(CC) -c $(COPT) $<

$(MOCC): moc_%.cpp: %.h
	$(MOC) -o $@ $<

.PHONY: clean
clean:
	rm -f $(OBJS) $(MOCC)

run: $(TARG)
	./$(TARG)
